package CornLanguage.sandbox;

/*Generated by MPS */

import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import java.util.List;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import jetbrains.mps.internal.collections.runtime.IVisitor;

public class map_Research {
  public map_Research() {
  }

  public static void main(String[] args) {
    System.out.println("Название исследования: " + "наше первое исследование");
    calculate(0, ListSequence.fromList(new ArrayList<Integer>()), ListSequence.fromList(new ArrayList<Integer>()));
  }

  public static void calculate(int numberOfMeasurements, List<Integer> stemLengths, List<Integer> blueDepths) {
    ++numberOfMeasurements;
    ListSequence.fromList(stemLengths).addElement(2);
    ListSequence.fromList(blueDepths).addElement(5);
    ++numberOfMeasurements;
    ListSequence.fromList(stemLengths).addElement(3);
    ListSequence.fromList(blueDepths).addElement(2);
    ++numberOfMeasurements;
    ListSequence.fromList(stemLengths).addElement(5);
    ListSequence.fromList(blueDepths).addElement(120);
    ++numberOfMeasurements;
    ListSequence.fromList(stemLengths).addElement(2);
    ListSequence.fromList(blueDepths).addElement(2);
    ++numberOfMeasurements;
    ListSequence.fromList(stemLengths).addElement(55);
    ListSequence.fromList(blueDepths).addElement(2);
    final Wrappers._int stemLengthsSum = new Wrappers._int(0);
    final Wrappers._int blueDepthsSum = new Wrappers._int(0);
    ListSequence.fromList(stemLengths).visitAll(new IVisitor<Integer>() {
      public void visit(Integer it) {
        stemLengthsSum.value += it;
      }
    });
    ListSequence.fromList(blueDepths).visitAll(new IVisitor<Integer>() {
      public void visit(Integer it) {
        blueDepthsSum.value += it;
      }
    });
    System.out.println("Количество измерений: " + numberOfMeasurements);
    System.out.println("Средняя длина стебля: " + stemLengthsSum.value / numberOfMeasurements);
    System.out.println("Средняя глубина синего: " + blueDepthsSum.value / numberOfMeasurements);
  }
}
